### ISSUE TITLE
united kingdom not on map

### ISSUE THREAD

**Issue by adaschevici** [tourhero/travel-reopening#9]
United kingdom missing from lookup
![image](https://user-images.githubusercontent.com/1737522/85517823-8a4be280-b5f7-11ea-8e43-56547d2ae7cf.png)

**Comment by yurikoval** [comment]
Hey @adaschevici. `United Kingdom` is listed under `UK`, however I understand the full name is more common for search so I've updated it to `United Kingdom` in https://github.com/tourhero/travel-reopening/pull/10 We will consider adding search aliases in the future.
